language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install numpy scipy matplotlib codecov

script:
  - coverage run --source=colour -m unittest test_colour/test_data.py

after_success:
  - codecov
