language: python
env:
   - NUMPY_VERSION=1.11.0
   - NUMPY_VERSION=1.12.1
   - SCIPY_VERSION=0.17.0
   - SCIPY_VERSION=0.19.0
python:
  - "3.5"
  - "3.6"
install:
  - pip install numpy==$NUMPY_VERSION scipy==$SCIYY_VERSION matplotlib
script:
  - python -m unittest test_colour/test_data.py
